CREATE OR REPLACE TABLE `sadaindia-tvm-poc-de.abdu_dataset.Employee_final_table`(
Project_ID  INT64,
Emp_id  INT64,
Client_ID INT64,
ProjectName STRING,
Proj_Start_Dt DATE,
Proj_End_Dt DATE,
Project_Cost  FLOAT64,
Project_Domain  STRING,
Project_Internal_URL  STRING,
Project_Username STRING,
Project_tag STRING,
Project_Owner STRING,
Project_Time_Zone STRING,
Project_Contact STRING,
Project_Description STRING,
Clientf_Name  STRING,
Clientl_Name  STRING,
Client_Parent_Company STRING,
Client_Eml  STRING,
Client_Phone_No STRING,
Age  INT64,
Country STRING,
Client_City STRING,
Street_Address  STRING,
Client_Time_Zone  STRING ,
Postal_Code STRING,
Capital_Income  STRING,
Work_Sector STRING,
Retail_Department STRING,
Domain_Name STRING,
Client_Site STRING,
Client_App_ID STRING,
Client_App_Name STRING,
Workforce_Requirement STRING,
Empf_name STRING,
Empl_name STRING,
Joining_Date  DATE,
Empl_Eml  STRING,
PhoneNo STRING,
Job_Title STRING,
Department  STRING,
Language STRING,
City  STRING,
State STRING,
Postal_Cd STRING,
Country_Cd  STRING,
Time_Zone STRING,
Street_Add  STRING,
Street_Nm STRING,
Street_suffix STRING,
Street_No INT64,
Salary  FLOAt64,
Expertise STRING,
Gender  STRING,
Race  STRING,
EIN_No  STRING,
EmpDevice_Ip  STRING,
EmpDevice_Mac STRING,
Emp_Prof  STRING,
Buzzword  STRING,
Geography_point GEOGRAPHY,
Application STRING,
Relation_string STRING   );

INSERT INTO
`sadaindia-tvm-poc-de.abdu_dataset.Employee_final_table`(Project_ID,
   Emp_id,
   Client_ID,
   ProjectName,
   Proj_Start_Dt,
   Proj_End_Dt,
   Project_Cost,
   Project_Domain,
   Project_Internal_URL,
   Project_Username,
   Project_tag,
   Project_Owner,
   Project_Time_Zone,
   Project_Contact,
   Project_Description,
   Clientf_Name,
   Clientl_Name,
   Client_Parent_Company,
   Client_Eml,
   Client_Phone_No,
   Age,
   Country,
   Client_City,
   Street_Address,
   Client_Time_Zone,
   Postal_Code,
   Capital_Income,
   Work_Sector,
   Retail_Department,
   Domain_Name,
   Client_Site,
   Client_App_ID,
   Client_App_Name,
   Workforce_Requirement,
   Empf_name,
   Empl_name,
   Joining_Date,
   Empl_Eml,
   PhoneNo,
   Job_Title,
   Department,
   Language,
   City,
   State,
   Postal_Cd,
   Country_Cd,
   Time_Zone,
   Street_Add,
   Street_Nm,
   Street_suffix,
   Street_No,
   Salary,
   Expertise,
   Gender,
   Race,
   EIN_No,
   EmpDevice_Ip,
   EmpDevice_Mac,
   Emp_Prof,
   Buzzword,
   Geography_point,
   Application,
   Relation_string )
SELECT
   Project_ID,
   Emp_id,
   Client_ID,
   ProjectName,
   Proj_Start_Dt,
   Proj_End_Dt,
   Project_Cost,
   Project_Domain,
   Project_Internal_URL,
   Project_Username,
   Project_tag,
   Project_Owner,
   Project_Time_Zone,
 REPLACE(Project_Contact,'-','') AS Project_Contact,
   Project_Description,
   Clientf_Name,
   Clientl_Name,
   Client_Parent_Company,
   Email_x,
   Phone_No,
   Age,
   Country,
   Client_City,
   Street_Address,
   Client_Time_Zone,
   Postal_Code,
   Capital_Income,
   Work_Sector,
   Retail_Department,
   Domain_Name,
   Client_Site,
   Client_App_ID,
   Client_App_Name,
   Workforce_Requirement,
   Empf_name,
   Empl_name,
   Joining_Date,
   Email_y,
   PhoneNo,
   Job_Title,
   Department,
   Language,
   City,
   State,
   Postal_Cd,
   Country_Cd,
   Time_Zone,
   Street_Add,
   Street_Nm,
   Street_suffix,
   Street_No,
   Salary,
   Expertise,
    CASE
   WHEN Gender="M" THEN "Male"
 ELSE "Female"
END,
   Race,
   REPLACE (EIN_No,'-','') AS EIN_No,
   EmpDevice_Ip,
   EmpDevice_Mac,
   Emp_Prof,
   Buzzword,
   ST_GEOGPOINT(longitude, latitude) AS Geography_point,
   CONCAT(Client_APP_NAME,'@',Client_ID) AS Application,
   CONCAT (Emp_id,'-',Project_ID,'-',Client_ID) AS Relation_string
 ,
 FROM
 `sadaindia-tvm-poc-de.abdu_dataset.Employee_staging_table`


